name: Generate Gallery JSON

on:
  push:
    branches:
      - main  # Adjust this if you use a different default branch

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure you're using a compatible Node.js version

      - name: Install dependencies
        run: npm install

      - name: Generate gallery.json
        run: node generate-gallery-json.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add gallery.json
          git commit -m 'Update gallery.json'
          git push
          
